NumPy. (numpi)) es una biblioteca para el lenguaje de programación Python que da soporte para crear vectores y matrices grandes multidimensionales, junto con una gran colección de funciones matemáticas de alto nivel para operar con ellas.

In [2]:
import numpy as np

## 1. Crando array

In [3]:
a = np.array([1,2,3])
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]], dtype = float)

In [4]:
np.zeros((3,4)) 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## 2. Creando Array de unos

In [5]:
np.ones((2,3,4),dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

## 3. Array uniforme

In [7]:
d = np.arange(10,25,5)
np.linspace(0,2,9) 

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

## 4. Array constante

In [9]:
 e = np.full((2,2),7)

## 5. Matriz 2*2

In [10]:
 f = np.eye(2)

## 6. Array con valores aleatorios 

In [11]:
np.random.random((2,2))

array([[0.20633658, 0.89791325],
       [0.12774669, 0.91699024]])

## 7. Array vacio 

In [12]:
np.empty((3,2)) 

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

## 8. Guardando y cargando de disco

In [13]:
np.save('my_array', a)

In [14]:
 np.savez('array.npz', a, b)

 np.load('my_array.npy')

## 9. Guardando y cargando texto plano

In [ ]:
np.loadtxt("numbers.txt")

In [ ]:
array([ 25.,  10., 100.])

In [ ]:
 np.genfromtxt("archivoSVC.csv", delimiter=',')

In [ ]:
array([nan, 90., 20.])

In [ ]:
np.savetxt("myarray.txt", a, delimiter=" ")

## 10. Tipos de datos 

## 11.  1.Tipos enteros de 64 bits firmados

In [20]:
print("1")
np.int64

1


numpy.int64

## 12. 2. Coma flotante estándar de doble precisión 

In [21]:
print("2")
np.float32

2


numpy.float32

## 13 . 3. Números complejos representados por 128 flotadores

In [22]:
print("3")
np.complex

3


complex

## 14. 4. Tipo booleano que almacena valores TRUE y FALSE

In [23]:
print("4")
np.bool

4


bool

## 15. 5.Tipo de objeto Python

In [24]:
print("5")
np.object

5


object

## 16. 6.Tipo de cadena de longitud fija

In [25]:
print("6")
np.string_

6


numpy.bytes_

## 17. 7.Tipo unicode de longitud fija

In [26]:
print("7")
np.unicode_

7


numpy.str_

## 18. Inspeccionando los arreglos

In [27]:
print("1.Dimensión del arreglo = ", a.shape)
print("2.Tamaño del arreglo = ", len(a))
print("3.Número de dimensiones del arreglo = ", b.ndim)
print("4.Número de elementos en el arreglo = ", e.size)
print("5.Tipo de datos de los elementos del arreglo = ", b.dtype)
print("6.Nombre de los tipos de datos = ", b.dtype.name)
print("7.Convertir un array a otro tipo de dato => \n", b.astype(int))

1.Dimensión del arreglo =  (3,)
2.Tamaño del arreglo =  3
3.Número de dimensiones del arreglo =  2
4.Número de elementos en el arreglo =  4
5.Tipo de datos de los elementos del arreglo =  float64
6.Nombre de los tipos de datos =  float64
7.Convertir un array a otro tipo de dato => 
 [[1 2 3]
 [4 5 6]]


## 19. Pidiendo ayuda

In [28]:
np.info(np.ndarray.dtype)

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


## 20 . Arrglos matemáticos
### Operaciones aritméticas

## 21 . Sustracción

In [30]:
print("Sustracción")
g = a - b
np.subtract(a,b)

Sustracción


array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

## 22 . Adición

In [31]:
print("Adición")
b + a
np.add(b,a)

Adición


array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

## 23. División

In [32]:
print("División")
a / b 
np.divide(a,b)

División


array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

## 24. Multiplicación

In [33]:
print("Multiplicación")
a * b
np.multiply(a,b)

Multiplicación


array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

## 25. Exponente

In [34]:
print("Exponente")
np.exp(b)

Exponente


array([[  4.48168907,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

## 26. Raiz

In [35]:
print("Raiz")
np.sqrt(b)

Raiz


array([[1.22474487, 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

## 27. Seno del arreglo

In [36]:
print("Seno del arreglo")
np.sin(a)

Seno del arreglo


array([0.84147098, 0.90929743, 0.14112001])

## 28. Coseno del arreglo

In [37]:
print("Coseno del arreglo")
np.cos(b)

Coseno del arreglo


array([[ 0.0707372 , -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

## 29. Logaritmo del arreglo

In [38]:
print("Logaritmo del arreglo")
np.log(a)

Logaritmo del arreglo


array([0.        , 0.69314718, 1.09861229])

## 30. Producto del arreglo

In [39]:
print("Producto del arreglo")
e.dot(f)

Producto del arreglo


array([[7., 7.],
       [7., 7.]])

# 31. Comparaciones

In [40]:
a == b

array([[False,  True,  True],
       [False, False, False]])

In [41]:
a < 2 

array([ True, False, False])

In [42]:
np.array_equal(a, b)

False

## 32. Agregar funciones

In [43]:
print("La suma del array es : ", a.sum())

La suma del array es :  6


In [44]:
print("El valor mínimo del arreglo es : ", a.min())

El valor mínimo del arreglo es :  1


In [45]:
print("El valor máximo de una columna del array es : ", b.max(axis=0))

El valor máximo de una columna del array es :  [4. 5. 6.]


In [46]:
print("Suma acumulativa de los elementos del arreglo : ", b.cumsum(axis=1))

Suma acumulativa de los elementos del arreglo :  [[ 1.5  3.5  6.5]
 [ 4.   9.  15. ]]


In [47]:
print("Media : ", a.mean())

Media :  2.0


In [51]:
b.median ()
a.corrcoef ()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [49]:
print("Desvición estndAr: ", np.std(b))

Desvición estndAr:  1.5920810978785667


## 33. Copiando arreglos

In [52]:
h = a.view()

In [53]:
np.copy(a)

array([1, 2, 3])

In [54]:
h = a.copy()
print(h)

[1 2 3]


## 34.  Ordenando arreglos

In [55]:
a.sort()
c.sort(axis=0)

## 35. Subconfiguración, segmentación, indexación

In [56]:
print("Subconfiguración")
a[2]

Subconfiguración


3

In [57]:
b[1,2]

6.0

## 36 Segmentación

In [58]:
 a[0:2]

array([1, 2])

In [59]:
b[0:2,1]

array([2., 5.])

In [60]:
b[:1]

array([[1.5, 2. , 3. ]])

In [61]:
c[1,...]

array([[3., 2., 3.],
       [4., 5., 6.]])

In [62]:
 a[ : :-1]

array([3, 2, 1])

## 37. Indexando loleanos

In [63]:
a[a<2]

array([1])

## 38. Indexación de fantasía

In [64]:
b[[1, 0, 1, 0],[0, 1, 2, 0]]

array([4. , 2. , 6. , 1.5])

In [65]:
b[[1, 0, 1, 0]][:,[0,1,2,0]]

array([[4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5],
       [4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5]])

## 39 . Manipulación de arreglos
## Transponer arreglos

In [66]:
i = np.transpose(b)

In [67]:
i.T

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

## 40. Cambiando la forma del arreglo

In [68]:
b.ravel()

array([1.5, 2. , 3. , 4. , 5. , 6. ])

In [69]:
g.reshape(3,-2)

array([[-0.5,  0. ],
       [ 0. , -3. ],
       [-3. , -3. ]])

## 41. Agregando y removiendo elementos

In [70]:
h.resize((2,6))

In [71]:
 np.append(h,g)

array([ 1. ,  2. ,  3. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
        0. , -0.5,  0. ,  0. , -3. , -3. , -3. ])

In [72]:
 np.insert(a, 1, 5)

array([1, 5, 2, 3])

In [73]:
np.delete(a,[1])

array([1, 3])

## 42. Combinando arreglos

In [74]:
np.concatenate((a,d),axis=0)

array([ 1,  2,  3, 10, 15, 20])

In [75]:
np.vstack((a,b))

array([[1. , 2. , 3. ],
       [1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [76]:
np.r_[e,f]

array([[7., 7.],
       [7., 7.],
       [1., 0.],
       [0., 1.]])

In [77]:
np.hstack((e,f))

array([[7., 7., 1., 0.],
       [7., 7., 0., 1.]])

In [78]:
np.column_stack((a,d))

array([[ 1, 10],
       [ 2, 15],
       [ 3, 20]])

In [79]:
np.c_[a,d]

array([[ 1, 10],
       [ 2, 15],
       [ 3, 20]])

## 43. Separación de arreglos

In [81]:
 np.hsplit(a,3)

[array([1]), array([2]), array([3])]

In [82]:
np.vsplit(c,2)

[array([[[1.5, 2. , 1. ],
         [4. , 5. , 6. ]]]), array([[[3., 2., 3.],
         [4., 5., 6.]]])]